server:
  port: 8572




#\u5411eureka\u6CE8\u518C
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      #\u6CE8\u518C\u5730\u5740
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: mqTransation

#mq配置H
  rabbitmq:
    host: 192.168.1.78
    port: 5672
    username: admin
    password: admin
    #\u5730\u5740\u865A\u62DF\u7A7A\u95F4
    virtual-host: /
    #\u5F00\u542F\u6D88\u606F\u786E\u8BA4\u673A\u5236 confirms
    publisher-confirms: true
    publisher-returns: true


 #使用环境
  profiles:
    active: dev


#redis配置
  redis:
    host: 127.0.0.1
    port: 6379