#设置不能让自己检查自己发现服务注册
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      #设置与Eureka Server交互的地址，查询服务和注册服务都需要依赖这个地址。默认是http://localhost:8761(UI界面)/eureka ；多个地址可使用 , 分隔。
      defaultZone: http://root:admin@${eureka.instance.hostname}:${server.port}/eureka/
  instance:
    hostname: localhost

  server:
    #关闭自我保护模式
    enable-self-preservation: false



spring:
  application:
    name: eureka-server
server:
  port: 8761

